/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyButton {
    /**
    * Disable button
    */
    'disabled'?: boolean;
    /**
    * Make button grow to 100%
    */
    'fluid'?: boolean;
    /**
    * Button kind
    */
    'kind'?: "default" | "primary" | "danger";
    /**
    * Optional string that can be used to set the button value
    */
    'text'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyInput {}
}

declare global {


  interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {}
  var HTMLMyButtonElement: {
    prototype: HTMLMyButtonElement;
    new (): HTMLMyButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {}
  var HTMLMyInputElement: {
    prototype: HTMLMyInputElement;
    new (): HTMLMyInputElement;
  };
  interface HTMLElementTagNameMap {
    'my-button': HTMLMyButtonElement;
    'my-component': HTMLMyComponentElement;
    'my-input': HTMLMyInputElement;
  }
}

declare namespace LocalJSX {
  interface MyButton extends JSXBase.HTMLAttributes<HTMLMyButtonElement> {
    /**
    * Disable button
    */
    'disabled'?: boolean;
    /**
    * Make button grow to 100%
    */
    'fluid'?: boolean;
    /**
    * Button kind
    */
    'kind'?: "default" | "primary" | "danger";
    /**
    * Optional string that can be used to set the button value
    */
    'text'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyInput extends JSXBase.HTMLAttributes<HTMLMyInputElement> {}

  interface IntrinsicElements {
    'my-button': MyButton;
    'my-component': MyComponent;
    'my-input': MyInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


